### ISSUE TITLE
Todo-list of fixes and improvements

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/digistuff#2]
**Mod stuff**
* [ ] Add luacheck
* [ ] Use mod.conf
* [ ] Move documentation in readme to separate files

**Bugs**
* [ ] Fix piston ignoring protection (pandorabox-io/pandorabox.io#616)
* [ ] Add fix for NIC (pandorabox-io/pandorabox.io#539)
* [ ] Fix game controller physics override
* [ ] Fix movestone (might be fixed on upstream, as it is a new feature)

**Improvements**
* [ ] Add ability to POST with NIC (pandorabox-io/pandorabox.io#183)
* [ ] Add support for more formspec elements in touchscreen

**Comment by S-S-X** [comment]
Could also revisit custom headers support when/if adding support for POST requests, basic stuff without cleanup was part of JSON support PR but did not make it into final product: https://github.com/mt-mods/digistuff/commit/0d2d670c9e32425478f16006637958d97a51789c
Also on PR there's comment with simple header data cleanup code: https://github.com/mt-mods/digistuff/pull/17#issuecomment-792403068
